// stores/productStore.js
import { defineStore } from 'pinia';

export const useProductStore = defineStore('productStore', {
  state: () => ({
    products: [
      {
        id: 1,
        title: 'مک بوک',
        quantity: 3,
        category: 'laptop',
        subCategory: 'اپل مک بوک',
        productCode: 'G-1001',
        rating: 5,
        price: 116_500_000,
        bestProduct: true,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 2,
        title: 'پردازنده اینتل Core i9',
        quantity: 3,
        category: 'laptop',
        subCategory: 'پرینتر لیزری',
        productCode: 'G-1002',
        rating: 5,
        price: 11_500_000,
        bestProduct: true,
        discountPercentage: 0,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 3,
        title: 'مک بوک',
        quantity: 3,
        category: 'phone',
        subCategory: 'اپل',
        productCode: 'G-1003',
        rating: 5,
        price: 16_500_000,
        bestProduct: true,
        discountPercentage: 0,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 4,
        title: 'مک',
        quantity: 3,
        category: 'phone',
        subCategory: 'اپل',
        productCode: 'G-1004',
        rating: 5,
        price: 116_100_000,
        bestProduct: true,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 5,
        title: 'بوک',
        quantity: 3,
        category: 'phone',
        subCategory: 'اپل',
        productCode: 'G-1005',
        rating: 5,
        price: 1_500_000,
        bestProduct: true,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 6,
        title: 'مک بوک',
        quantity: 3,
        category: 'phone',
        subCategory: 'اپل',
        productCode: 'G-1006',
        rating: 5,
        price: 116_500_000,
        bestProduct: true,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 7,
        title: 'مک بوک',
        quantity: 3,
        category: 'phone',
        subCategory: 'اپل',
        productCode: 'G-1007',
        rating: 5,
        price: 116_500_000,
        bestProduct: false,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 8,
        title: 'مک بوک',
        quantity: 3,
        category: 'laptop',
        subCategory: 'اپل مک بوک',
        productCode: 'G-1008',
        rating: 5,
        price: 116_500_000,
        bestProduct: false,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 9,
        title: 'مک بوک',
        quantity: 3,
        category: 'laptop',
        subCategory: 'اپل مک بوک',
        productCode: 'G-1009',
        rating: 5,
        price: 116_500_000,
        bestProduct: false,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
      {
        id: 10,
        title: 'مک بوک',
        quantity: 3,
        category: 'laptop',
        subCategory: 'اپل مک بوک',
        productCode: 'G-1010',
        rating: 5,
        price: 116_500_000,
        bestProduct: false,
        discountPercentage: 10,
        image: '../../public/images/products/macbook-pro-13-m1-2020-silver.webp',
        creationDate: '2025-01-01',
        description: 'این یک محصول نمونه است.',
        technicalSpecifications: {
          weight: '1kg',
          dimensions: '20x30x10cm',
          color: 'مشکی',
          warranty: '12 ماه',
        },
      },
    ],
  }),

  getters: {
    allProducts: (state) => state.products,

    productsByCategory: (cat) => {
      return (category) => cat.products.filter(product => product.category === category);
    },

    productById: (state) => {
      return (id) => state.products.find(product => product.id === id);
    }
  }
});
